# Generated by Django 3.0.4 on 2020-03-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_personnel', '0003_auto_20200314_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
