# Generated by Django 3.0.4 on 2020-03-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_personnel', '0004_auto_20200314_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Professor',
        ),
    ]
